OTDAV/Controllers/UserMembershipController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Newtonsoft.Json;
using OTDAV.Core;
using OTDAV.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OTDAV.Controllers
{
    public class UserMembershipController : Controller
    {

        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;


        public UserMembershipController()
        {

        }

        public UserMembershipController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;


        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        // GET: Membership
        public async Task<ActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                //this function add headers and other things like request return format ( json )
                client.PrepareForRequest(JavaSpring.MEMBERSHIPS, User.Identity.Name);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.MEMBERSHIPS);
                if (response.IsSuccessStatusCode)
                {
                    string rawData = await response.Content.ReadAsStringAsync();
                    ICollection<Areas.Admin.Models.Membership> list = JsonConvert.DeserializeObject<ICollection<Areas.Admin.Models.Membership>>(rawData);
                    return View(list);
                }
                else
                {
                    return View(new List<Areas.Admin.Models.Membership>());
                }
            }
        }

        // GET: Membership/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult CreateMembershipOnly()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateMembershipOnly(Membership collection)
        {
            // creation first time membership
            using (HttpClient clientMembership = new HttpClient())
            {
                //collection.user = null;
                clientMembership.PrepareForRequest(JavaSpring.MEMBERSHIPS, User.Identity.Name);
                HttpResponseMessage membershipResponse = await clientMembership.PostAsJsonAsync(JavaSpring.MEMBERSHIPS, collection);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Membership/Create
        public async Task<ActionResult> Create()
        {
            using (HttpClient client = new HttpClient())
            {
                client.PrepareForRequest(JavaSpring.GUESTS);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.GUESTS);
                if (response.IsSuccessStatusCode)
                {
                    var rawData = await response.Content.ReadAsStringAsync();
                    ICollection<OTDAV.Areas.Admin.Models.User> list = JsonConvert.DeserializeObject<ICollection<OTDAV.Areas.Admin.Models.User>>(rawData);
                    if(list.Count == 0)
                    {
                        return RedirectToAction("CreateMembershipOnly");
                    }
                    Membership m  = new Membership();
                    m.stat = "In_progress";
                    m.user = list.Where(u=> u.email == User.Identity.Name).FirstOrDefault();
                    m.user.moral = true;
                    m.user.isSubscribed = true;
                    return View(m);
                }
                else
                {
                    return View();
                }
            }
        }

        // POST: Membership/Create
        [HttpPost]
        public async Task<ActionResult> Create(Membership collection)
        {
            try
            {


                using (HttpClient client = new HttpClient())
                {
                    //this function add headers and other things like request return format ( json )
                    client.PrepareForRequest(JavaSpring.USERS +"/save");
                    HttpResponseMessage response = await client.PostAsJsonAsync(JavaSpring.USERS + "/save", collection.user);
                    if (response.IsSuccessStatusCode)
                    {
                        var rawData = await response.Content.ReadAsStringAsync();
                        //Membership membership = JsonConvert.DeserializeObject<Membership>(rawData);
                        var currentUser = await UserManager.FindByEmailAsync(User.Identity.Name);
                        await UserManager.RemoveFromRoleAsync(currentUser.Id, "guest");
                        var roleresult = await UserManager.AddToRoleAsync(currentUser.Id, "user");
                        // creation first time membership
                        using (HttpClient clientMembership = new HttpClient())
                        {
                            collection.user = null;
                            clientMembership.PrepareForRequest(JavaSpring.MEMBERSHIPS, User.Identity.Name);
                            HttpResponseMessage membershipResponse = await clientMembership.PostAsJsonAsync(JavaSpring.MEMBERSHIPS, collection);
                            await SignInManager.SignInAsync(currentUser, isPersistent: false, rememberBrowser: false);
                        }
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return View(collection);
                    }

                }

            }
            catch
            {
                return View();
            }
        }

        // GET: Membership/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Membership/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Membership/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Membership/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OTDAV/Controllers/WorkController.cs
using Newtonsoft.Json;
using OTDAV.Areas.Admin.Models;
using OTDAV.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace OTDAV.Controllers
{
    public class WorkController : Controller
    {
        // GET: Work
        public async Task<ActionResult> Index()
        {
            using (HttpClient client = new HttpClient())
            {
                //this function add headers and other things like request return format ( json )
                client.PrepareForRequest(JavaSpring.WORK, User.Identity.Name);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.WORK);
                if (response.IsSuccessStatusCode)
                {
                    string rawData = await response.Content.ReadAsStringAsync();
                    ICollection<OTDAV.Areas.Admin.Models.Work> list = JsonConvert.DeserializeObject<ICollection<OTDAV.Areas.Admin.Models.Work>>(rawData);
                    return View(list);
                }
                else
                {
                    return View(new List<OTDAV.Areas.Admin.Models.Work>());
                }
            }
        }

        // GET: Work/Details/5
        public async Task<ActionResult> Details(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                //this function add headers and other things like request return format ( json )
                client.PrepareForRequest(JavaSpring.WORK + "/" + id);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.WORK + "/" + id);
                if (response.IsSuccessStatusCode)
                {
                    var rawData = await response.Content.ReadAsStringAsync();
                    Work work = JsonConvert.DeserializeObject<Work>(rawData);
                    return View(work);
                }
                else
                {
                    return View();
                }
            }
        }

        public async Task<ICollection<WorkCategory>> RetriveWorkCategory()
        {
            List<WorkCategory> WorkCategoryList = new List<WorkCategory>();
            using (HttpClient client = new HttpClient())
            {
                //this function add headers and other things like request return format ( json )
                client.PrepareForRequest(JavaSpring.WORKCATEGORY);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.WORKCATEGORY);
                if (response.IsSuccessStatusCode)
                {
                    string rawData = await response.Content.ReadAsStringAsync();
                    ICollection<WorkCategory> list = JsonConvert.DeserializeObject<ICollection<WorkCategory>>(rawData);
                    return list;
                }
            }
            return null;
        }
        // GET: Work/Create
        public ActionResult Create()
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    ICollection<WorkCategory> result = Task.Run(RetriveWorkCategory).Result;
                    List<SelectListItem> ListWorkCategorie = result.Select(workCat =>
                   {
                       return new SelectListItem() { Text = workCat.title, Value = workCat.id.ToString() };
                   }).ToList();
                    ViewBag.ListWorkCategorie = ListWorkCategorie;
                    return View();
                }
            }
            catch
            {
                return View();
            }

        }

        // POST: Admin/WorkCategory/Create
        [HttpPost]
        public async Task<ActionResult> Create(Work CurWork)
        {
            Notification NewNotif = new Notification();
            ICollection<Membership> CurMembership = null;

            try
            {
                HttpClient NotificationClient = new HttpClient();
                NewNotif.stat = "In_progress";
                NewNotif.date = DateTime.Now;
                NotificationClient.PrepareForRequest(JavaSpring.NOTIFICATION);
                HttpResponseMessage NotificationResponse = await NotificationClient.PostAsJsonAsync(JavaSpring.NOTIFICATION, NewNotif);
                if (NotificationResponse.IsSuccessStatusCode)
                {
                    var rawData = await NotificationResponse.Content.ReadAsStringAsync();
                    int test = rawData.LastIndexOf('=') + 1;
                    int test1 = rawData.Length - 1;
                    string id = rawData.Substring(test);
                    NewNotif.id = Convert.ToInt32(id);
                    CurWork.notification = NewNotif;
                }
            }
            catch (HttpRequestException ex)
            {
                return View();
            }

            try
            {
                HttpClient MemberShipClient = new HttpClient();
                //MemberShip
                {
                    MemberShipClient.PrepareForRequest(JavaSpring.MEMBERSHIPS, User.Identity.Name);
                    HttpResponseMessage MemberShipResponse = await MemberShipClient.GetAsync(JavaSpring.MEMBERSHIPS);
                    if (MemberShipResponse.IsSuccessStatusCode)
                    {
                        string rawData = await MemberShipResponse.Content.ReadAsStringAsync();
                        CurMembership = JsonConvert.DeserializeObject<ICollection<Membership>>(rawData);
                        CurWork.membership = CurMembership.ElementAt(0);
                        MemberShipClient.Dispose();
                    }
                }
            }
            catch (HttpRequestException ex)
            {
                return View();
            }

            try
            {
                if (CurMembership != null)
                {
                    HttpClient WorkClient = new HttpClient();
                    WorkClient.PrepareForRequest(JavaSpring.WORK, User.Identity.Name);
                    HttpResponseMessage WorkCreaionResponse = await WorkClient.PostAsJsonAsync(JavaSpring.WORK, CurWork);
                    if (WorkCreaionResponse.IsSuccessStatusCode)
                    {
                        var rawData = await WorkCreaionResponse.Content.ReadAsStringAsync();
                        int test = rawData.LastIndexOf('=') + 1;
                        int test1 = rawData.Length - 1;
                        string id = rawData.Substring(test);
                        CurWork.id = Convert.ToInt32(id);

                        WorkClient.Dispose();
                    }
                }
            }
            catch (HttpRequestException ex)
            {
                return View();
            }

            if (CurWork.distributionRights != null)
            {
                foreach (OTDAV.Areas.Admin.Models.DistributionRight item in CurWork.distributionRights)
                {
                    try
                    {
                        OTDAV.Models.DistributionRight TempDistrubtionRight = new OTDAV.Models.DistributionRight();

                        TempDistrubtionRight.work = new OTDAV.Models.Work();
                        TempDistrubtionRight.membership = new OTDAV.Models.Membership();

                        TempDistrubtionRight.id = item.id;
                        TempDistrubtionRight.price = item.price;
                        TempDistrubtionRight.work.id = CurWork.id;
                        TempDistrubtionRight.description = item.description;
                        TempDistrubtionRight.startingDate = item.startingDate;
                        TempDistrubtionRight.finishingDate = item.finishingDate;
                        TempDistrubtionRight.membership.id = CurMembership.ElementAt(0).id;

                        HttpClient DistrubtionRightclient = new HttpClient();
                        DistrubtionRightclient.PrepareForRequest(JavaSpring.DISTRUBTIONRIGHT);
                        HttpResponseMessage DistrubtionRightResponse = await DistrubtionRightclient.PostAsJsonAsync(JavaSpring.DISTRUBTIONRIGHT, TempDistrubtionRight);

                        if (DistrubtionRightResponse.IsSuccessStatusCode)
                        {
                            DistrubtionRightclient.Dispose();
                        }
                    }
                    catch (HttpRequestException ex)
                    {
                        return View();
                    }
                }
            }
            return RedirectToAction("Index");
        }


        // GET: Work/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                //this function add headers and other things like request return format ( json )
                client.PrepareForRequest(JavaSpring.WORK + "/" + id);
                HttpResponseMessage response = await client.GetAsync(JavaSpring.WORK + "/" + id);
                if (response.IsSuccessStatusCode)
                {
                    var rawData = await response.Content.ReadAsStringAsync();
                    Work work = JsonConvert.DeserializeObject<Work>(rawData);
                    return View(work);
                }
                else
                {
                    return View();
                }
            }
        }

        // POST: Work/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Work collection)
        {
            try
            {
                using (HttpClient client = new HttpClient())
                {
                    //this function add headers and other things like request return format ( json )
                    client.PrepareForRequest(JavaSpring.WORK + "/" + id);
                    HttpResponseMessage response = await client.PutAsJsonAsync(JavaSpring.WORK + "/" + id, collection);

OTDAV/Views/UserMembership/Create.cshtml
@model OTDAV.Models.Membership

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>MemberShip</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.stat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stat, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.user.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.email, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.user.cin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.cin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.cin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.user.firstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.firstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.firstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.user.lastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.lastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.lastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-check">
        @Html.EditorFor(model => model.user.moral, new { htmlAttributes = new { @class = "form-check-input", id = "checkbox1" } })
        @Html.LabelFor(model => model.user.moral, htmlAttributes: new { @class = "form-check-label" })

        @Html.ValidationMessageFor(model => model.user.moral, "", new { @class = "text-danger" })
    </div>

    <div class="form-group moral">
        @Html.LabelFor(model => model.user.formeJuridique, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.user.formeJuridique, new List<SelectListItem>
{ new SelectListItem{ Text="SA", Value="SA"},
new SelectListItem{Text="SARL", Value="SARL"},
new SelectListItem{Text="SCA", Value="SCA"},
new SelectListItem{Text="SNC", Value="SNC"},
new SelectListItem{Text="SUARL", Value="SUARL"}}, "Please select", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.user.formeJuridique, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group moral">
        @Html.LabelFor(model => model.user.raisonSocial, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.raisonSocial, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.raisonSocial, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group moral">
        @Html.LabelFor(model => model.user.identifiantUnique, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.user.identifiantUnique, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.user.identifiantUnique, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    @Html.HiddenFor(model => model.user.id, new { htmlAttributes = new { @class = "form-control" } })


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#checkbox1').change(function () {
                if (this.checked) {
                     $('.moral').css('display', 'block');
                } else {
                    $('.moral').css('display', 'none');
                }
            });
        });
    </script>
    @Scripts.Render("~/bundles/jqueryval")
}

OTDAV/Views/UserMembership/CreateMembershipOnly.cshtml
@model OTDAV.Models.Membership

@{
    ViewBag.Title = "CreateMembershipOnly";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateMembershipOnly</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Membership</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.stat, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.stat, new { htmlAttributes = new { @readonly = true, @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.stat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OTDAV/Views/UserMembership/Index.cshtml
@model IEnumerable<OTDAV.Areas.Admin.Models.Membership>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Memberships</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div class="row">
    <div class="col-12">
        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.stat)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.description)
                </th>
                <th scope="col">
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>Actions</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.stat)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>

                        @*@Html.ActionLink("Edit", "Edit", new { id = item.id }) |
        @Html.ActionLink("Details", "Details", new { id = item.id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.id }) |*@
                        @Html.ActionLink("Manage ConstituentFile", "Index", "UserConstituentFile", new { id = item.id }, new { @class = "btn btn-primary" }) 

                        @if (item.stat == "Accepted")
                        {
                            @Html.ActionLink("Manage declarations", "Index", "UserDeclarations", new { id = item.id }, new { @class = "btn btn-primary" })

                            @Html.ActionLink("Manage works", "Index", "Work", new { @class = "btn btn-primary" })
                            @*@Html.ActionLink("Manage DistributionRights", "Index", "UserDistributionRight", new { id = item.id }, new { })*@

                        }

                        @*<button type="button" class="btn btn-primary"><i class="far fa-eye"></i></button>
                        <button type="button" class="btn btn-success"><i class="fas fa-edit"></i></button>
                        <button type="button" class="btn btn-danger"><i class="far fa-trash-alt"></i></button>*@
                    </td>
                </tr>
            }

        </table>
        </div>
    </div>